name: Build Windows EXE

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Clean Install Dependencies
        run: |
          npm ci || npm install

      - name: Package Application into EXE
        run: npm run dist
        env:
          ELECTRON_SKIP_NOTARIZATION: true

      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Executable
          path: "**/*.exe"
